name: CI Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: 📥 Checkout code
        uses: actions/checkout@v4

      - name: 🐍 Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.13"

      - name: 📦 Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest pytest-cov flake8 bandit

      - name: 🔍 Lint with flake8
        run: |
          flake8 src tests --max-line-length=120 --ignore=E203,W503

      - name: 🔐 Security check with Bandit
        run: |
          bandit -r src

      - name: 🧪 Run tests with coverage
        env:
          AWS_ACCESS_KEY_ID: fake_access_key
          AWS_SECRET_ACCESS_KEY: fake_secret_key
          AWS_REGION: us-east-1
          S3_BUCKET_NAME: expense-tracker-ashwini-4
          CLOUDWATCH_LOG_GROUP: test-logs
          PYTHONPATH: src
        run: |
          python -m pytest tests/ -v --cov=src --cov-report=xml --cov-report=html

      - name: 📊 Upload coverage report
        uses: actions/upload-artifact@v4
        with:
          name: coverage-report
          path: htmlcov
